### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by Rufino07** [SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-team-pro-1#1]
[DIAGRAMA DE CLASES1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-team-pro-1/files/14726986/DIAGRAMA.DE.CLASES1.pdf)

**Comment by yanet02** [comment]
**Calificación en base a la rúbrica:**

portada 25
procedimiento 20
firguras e ilustraciones: 25
resultado y conclusiones: 22
TOTAL=92
**Calificación Final: 18.4/ _20_**

Faltaron los objetivos, lista de material, hay errores ortograficos y resultados, lo demás bien hecho.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
